name: itsme

# helm chart repository
repos:
  - name: dbcafe-base
    url: https://code.db.cafe/api/packages/dbcafe/helm

# base installs
installs:
  - name: itsme
    chart: dbcafe-base/public-app

# environments
envs:
  - name: master
    namespace: itsme
    for:
      branch: master
    values:
      - prd.yaml
