import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <div>
          <h1 className={styles.firstName}>Mauricio</h1>
          <h3 className={styles.lastName}>Ferraz</h3>
        </div>

        <div>
          <Image src="/imgs/home-img.png" width="700px" height="600px" />
        </div>
      </main>
    </div>
  );
};

export default Home;
