name: Deploy
run-name: Deploy 🚀
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders          

      - name: Set up Docker Buildx
        id: buildx
        uses: https://github.com/docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
 
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/mauriciofsnts/itsme:${{ github.ref_name }}
